[package]
name = "miofib"
version = "0.1.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]

[dependencies]
mio = "0.6.6"
lazy_static = "*"
context = "1"
slog = { version = "2", features = ["max_level_trace", "release_max_level_debug"] }
slog-term = "~2.0.0-4"
slog-async = "2"
slab = "*"
