[package]
name = "miofib"
version = "0.1.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]

[dependencies]
mio = "0.6.6"
lazy_static = "*"
context = "1"
boxfnonce = "*"
slog = "~2.0.0-3"
slog-term = "~2.0.0-3"
slog-async = "~2.0.0-3"
slab = "*"
